language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install -r test/test-requirements.txt"
# command to run tests
script:
    - pytest --cov-report= --cov=renard test/
after_success:
    - coveralls
